image: ghcr.io/branjam4/guixsd-config:master
ports:
  - port: 6080
    onOpen: open-browser
    visibility: public
  - port: 5900
    onOpen: ignore
tasks:
  - name: qemu-vnc
    #init: sudo /home/gitpod/opt/gnu/bin/qemu-system-x86_64 -hda /emacs-vm.qcow2 -m 4000 -vnc :0
    command: /home/gitpod/opt/gnu/bin/virt-manager
github:
  prebuilds:
    branches: true
    addBadge: true
