(specifications->manifest
 '("emacs-ement"
   "emacs-crdt"
   "emacs-dtache"
   "emacs-elpher"
   "emacs-org-pandoc-import"
   "emacs-suggest"
   "emacs-ledger-mode"
   "emacs-ts"
   "miredo"
   "man-db"
   "emacs-hyperbole"))
